databases:
  - name: base
    databaseName: base_p559
    user: base_p559_user

services:
  - type: web
    name: owl
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: base
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false